id: J14
title: Solving Vertex Coloring Problems as Maximum Weight Stable Set Problems
authors:
- D. Cornaz
- F. Furini
- E. Malaguti
year: 2017
kind: journal
venue: Discrete Applied Mathematics, Elsevier.
status: published
doi: 10.1016/j.dam.2016.09.018
doi_url: https://doi.org/10.1016/j.dam.2016.09.018
preprint_url: null
themes:
- graph-coloring
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: 'Article history: In Vertex Coloring Problems, one is required to assign a color to each vertex
  of an undirected Received 19 June 2015 graph in such a way that adjacent vertices receive different
  colors, and the objective is to Received in revised form 20 July 2016 minimize the cost of the used
  colors. In this work we solve four different coloring problems Accepted 4 September 2016 formulated
  as Maximum Weight Stable Set Problems on an associated graph. We exploit Available online 29 September
  2016 the transformation proposed by Cornaz and Jost (2008), where given a graph G, an auxiliary'
