id: C05
title: State space reduced dynamic programming for the aircraft sequencing problem with constrained position
  shifting
authors:
- F. Furini
- M. P. Kidd
- A. Persiani
- P. Toth
year: 2014
kind: conference
venue: 4th International Symposium on Combinatorial Optimization (ISCO 2014), Lisbon, Portugal, March
  2014 (12 pages).
status: published
doi: null
doi_url: null
preprint_url: null
themes: []
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: In this paper we present state space reduction techniques for a dynamic programming algorithm
  applied to the Aircraft Sequencing Problem (ASP) with Constrained Position Shifting (CPS). We consider
  the classical version of the ASP, which calls for determining the order in which a given set of aircraft
  should be assigned to a runway at an airport, subject to minimum separations in time between consecutive
  aircraft, in order to minimize the sum of the weighted deviations from the scheduled arrival/departure
  times of the aircraft. The focus of the paper is on a number of ways of improving the computation times
  of the dynamic programming algorithm proposed. This is achieved by using heuristic upper bounds and
  a completion lower bound in order to reduce the state space in the dynamic programming algorithm. We
  compare our algorithm to an approach based on mixed integer linear programming, which was adapted from
  the literature for the case of CPS. We show using real-world air traﬃc instances from the Milan Linate
  Airport that the dynamic programming algorithm signiﬁcantly outperforms the MILP. Furthermore, we show
  that the proposed algorithm is capable of solving very large instances in short computation times, and
  that it is suitable for use in a real-time setting
