id: J20
title: On the Product Knapsack Problem
authors:
- C. D'Ambrosio
- F. Furini
- M. Monaci
- E. Traversi
year: 2018
kind: journal
venue: Optimization Letters, Springer.
status: published
doi: 10.1007/s11590-017-1227-5
doi_url: https://doi.org/10.1007/s11590-017-1227-5
preprint_url: null
themes:
- knapsack
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: Given a set of items, each characterized by a profit and a weight, we study the problem of maximizing
  the product of the profits of the selected items, while respecting a given capacity. To the best of
  our knowledge this is the first manuscript that studies this variant of the knapsack problem which we
  call Product Knapsack Problem (PKP). We show that PKP is weakly NP-hard. We propose and implement a
  Dynamic Programming algorithm and different Mixed Integer Linear and Nonlinear Programming formulations
  for the PKP. Finally, we present an extensive computa- tional study on a large set of benchmark instances
  derived from the literature
