id: J28
title: A new branch-and-bound algorithm for the Maximum Weighted Clique Problem
authors:
- P. San Segundo
- F. Furini
- J. Artieda
year: 2019
kind: journal
venue: Computer & Operations Research, Elsevier.
status: published
doi: 10.1016/j.cor.2019.05.017
doi_url: https://doi.org/10.1016/j.cor.2019.05.017
preprint_url: null
themes:
- clique-stable-set
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: We study the Maximum Weighted Clique Problem (MWCP), a generalization of the Maximum Clique
  Problem in which weights are associated with the vertices of a graph. The MWCP calls for determining
  a complete subgraph of maximum weight. We design a new combinatorial branch-and-bound algorithm for
  the MWCP, which relies on an effective bounding procedure. The size of the implicit enumeration tree
  is largely reduced via a tailored branching scheme, specifically conceived for the MWCP. The new bounding
  function extends the classical MWCP bounds from the literature to achieve a good trade off between pruning
  potential and computing effort. We perform extensive tests on random graphs, graphs from the literature
  and real-world graphs, and we computationally show that our new exact algorithm is competitive with
  the state-of-the-art algorithms for the MWCP in all these classes of instances
