id: J23
title: 'QPLIB: A Library of Quadratic Programming Instances'
authors:
- F. Furini
- E. Traversi
- P. Belotti
- A. Frangioni
- A. Gleixner
- N. Gould
- L. Liberti
- A. Lodi
- R. Misener
- H. Mittelmann
- N. Sahinidis
- S. Vigerske and A. Wiegele
year: 2019
kind: journal
venue: Mathematical Programming Computation, Springer.
status: published
doi: 10.1007/s12532-018-0147-4
doi_url: https://doi.org/10.1007/s12532-018-0147-4
preprint_url: null
themes:
- quadratic-programming
code_url: https://qplib.zib.de
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: This paper describes a new instance library for Quadratic Programming (QP), i.e., the family
  of continuous and (mixed)-integer optimization problems where the objective function, the constrains,
  or both are quadratic. QP is a very ``varied'' class of problems, comprising sub-classes of problems
  ranging from trivial to undecidable. Solution methods for QP are very diverse, ranging from entirely
  combinatorial ones to completely continuous ones, including many for which both aspects are fundamental.
  Selecting a set of instances of QP that is at the same time not overwhelmingly onerous but sufficiently
  challenging for the many different interested communities is therefore important. We propose a simple
  taxonomy for QP instances that leads to a systematic problem selection mechanism. We then briefly survey
  the field of QP, giving an overview of theory, methods and solvers. Finally, we describe how the library
  was put together, and detail its final contents.
