id: J41
title: Submodular maximization of concave utility functions composed with a set-union operator with applications
  to maximal covering location problems
authors:
- S. Coniglio
- F. Furini
- I. Ljubic
year: 2022
kind: journal
venue: Mathematical Programming, Springer.
status: published
doi: 10.1007/s10107-022-01884-7
doi_url: https://doi.org/10.1007/s10107-022-01884-7
preprint_url: null
themes:
- covering-location-submodular
code_url: https://github.com/fabiofurini/Maximizing-submodular-utility-functions
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: 'We study a family of discrete optimization problems asking for the maximization of the expected
  value of a concave, strictly increasing, and differentiable function composed with a set-union operator.
  The expected value is computed with respect to a set of coefficients taking values from a discrete set
  of scenarios. The function models the utility function of the decision maker, while the set-union operator
  models a covering relationship between two ground sets, a set of items and a set of metaitems. This
  problem generalizes the problem introduced by, and it can be modeled as a mixed integer nonlinear program
  involving binary decision variables associated with the items and metaitems. Its goal is to find a subset
  of metaitems that maximizes the total utility corresponding to the items it covers. It has applications
  to, among others, maximal covering location, and influence maximization problems. In the paper, we propose
  a double-hypograph decomposition which allows for projecting out the variables associated with the items
  by separately exploiting the structural properties of the utility function and of the set-union operator.
  Thanks to it, the utility function is linearized via an exact outer-approximation technique, whereas
  the set-union operator is linearized in two ways: either (i) via a reformulation based on submodular
  cuts, or (ii) via a Benders decomposition. We analyze from a theoretical perspective the strength of
  the inequalities of the resulting reformulations, and embed them into two branch-and-cut algorithms.
  We also show how to extend our reformulations to the case where the utility function is not necessarily
  increasing. We then experimentally compare our algorithms inter se, to a standard reformulation based
  on submodular cuts, to a state-of-the-art global-optimization solver, and to the greedy algorithm for
  the maximization of a submodular function. The results reveal that, on our testbed, the method based
  on combining an outer approximation with Benders cuts significantly outperforms the other ones.'
