id: C08
title: Lower Bounding Techniques for DSATUR-based Branch and Bound
authors:
- F. Furini
- V. Gabrel
- I. C. Ternier
year: 2015
kind: conference
venue: 7th International Network Optimization Conference (INOC 2015), Warsaw, Poland, June 2015 (8 pages).
status: published
doi: 10.1016/j.endm.2016.03.020
doi_url: https://doi.org/10.1016/j.endm.2016.03.020
preprint_url: null
themes: []
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: Given an undirected graph, the Vertex Coloring Problem (VCP) consists of assigning a color to
  each vertex of the graph such that two adjacent vertices do not share the same color and the total number
  of colors is minimized. DSATUR-based Branch- and-Bound is a well-known exact algorithm for the VCP.
  One of its main drawbacks is that a lower bound (equal to the size of a maximal clique) is computed
  once at the root of the branching scheme and it is never updated during the execution of the algorithm.
  In this article, we show how to update the lower bound and we compare the eﬃciency of several lower
  bounding techniques
