id: C01
title: Partial convexification of general MIPs by Dantzig-Wolfe reformulation
authors:
- M. Bergner
- A. Caprara
- F. Furini
- M.E. Lübbecke
- E. Malaguti
- E. Traversi
year: 2011
kind: conference
venue: 15th International Conference on Integer Programming and Combinatorial Optimization (IPCO 2011),
  New York, USA, June 2011 (12 pages).
status: published
doi: 10.1007/978-3-642-20807-2_4
doi_url: https://doi.org/10.1007/978-3-642-20807-2_4
preprint_url: null
themes: []
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: 'Dantzig-Wolfe decomposition is well-known to provide strong dual bounds for specially structured
  mixed integer programs (MIPs) in practice. However, the method is not implemented in any state-of-the-art
  MIP solver: it needs tailoring to the particular problem; the decomposi- tion must be determined from
  the typical bordered block-diagonal matrix structure; the resulting column generation subproblems must
  be solved eﬃciently; etc. We provide a computational proof-of-concept that the process can be automated
  in principle, and that strong dual bounds can be obtained on general MIPs for which a solution by a
  decomposition has not been the ﬁrst choice. We perform an extensive computational study on the 0-1 dynamic
  knapsack problem (without block-diagonal structure) and on general MIPLIB2003 instances. Our results
  support that Dantzig-Wolfe reformulation may hold more promise as a general- purpose tool than previously
  acknowledged by the research community'
