id: C03
title: Hybrid SDP Bounding Procedure
authors:
- F. Furini
- E. Traversi
year: 2013
kind: conference
venue: 12th International Symposium on Experimental Algorithms (SEA 2013), Rome, Italy, June 2013 (12
  pages).
status: published
doi: 10.1007/978-3-642-38527-8_23
doi_url: https://doi.org/10.1007/978-3-642-38527-8_23
preprint_url: null
themes: []
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: The principal idea of this paper is to exploit Semideﬁnite Programming (SDP) relaxation within
  the framework provided by Mixed Integer Nonlinear Programming (MINLP) solvers when tackling Binary Quadratic
  Problems. We included the SDP relaxation in a state-of-the- art MINLP solver as an additional bounding
  technique and demonstrated that this idea could be computationally useful. The Quadratic Stable Set
  Problem is adopted as the case study. The tests indicate that the Hy- brid SDP Bounding Procedure allows
  an average 50% cut of the overall computing time and a cut of more than one order of magnitude for the
  branching nodes
