id: J22
title: The Vertex k-cut Problem
authors:
- D. Cornaz
- F. Furini
- M. Lacroix
- E. Malaguti
- A. R. Mahjoub
- S. Martin
year: 2019
kind: journal
venue: Discrete Optimization, Elsevier.
status: published
doi: 10.1016/j.disopt.2018.07.003
doi_url: https://doi.org/10.1016/j.disopt.2018.07.003
preprint_url: null
themes:
- interdiction-blocker-vertex-cut
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: Given an undirected graph G = (V, E), a vertex k-cut of G is a vertex subset of V the removing
  of which disconnects the graph in at least k components. Given a graph G and an integer k ≥ 2, the vertex
  k-cut problem consists in finding a vertex k-cut of G of minimum cardinality. We first prove that the
  problem is NP-hard for any fixed k ≥ 3. We then present a compact formulation, and an extended formulation
  from which we derive a column generation and a branching scheme. Vertex cut Extensive computational
  results prove the effectiveness of the proposed methods. Mixed-integer programming models Branch and
  Price Exact algorithms
