id: J30
title: A note on selective line-graphs and partition colorings
authors:
- D. Cornaz
- F. Furini
- E. Malaguti
- A. Santini
year: 2019
kind: journal
venue: Operations Research Letters, Springer.
status: published
doi: 10.1016/j.orl.2019.08.005
doi_url: https://doi.org/10.1016/j.orl.2019.08.005
preprint_url: null
themes:
- graph-coloring
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: We extend a one-to-one correspondence between the set of all colorings of any graph and the
  set of all stable sets of an auxiliary graph, from graphs to partitioned graphs. This correspondence
  has an application to Selective Coloring and to Selective Max-Coloring.
