id: J37
title: A branch-and-cut algorithm for the Edge Interdiction Clique Problem
authors:
- F. Furini
- I. Ljubic
- P. San Segundo
- Y. Zhao
year: 2021
kind: journal
venue: European Journal of Operational Research, Elsevier.
status: published
doi: 10.1016/j.ejor.2021.01.030
doi_url: https://doi.org/10.1016/j.ejor.2021.01.030
preprint_url: null
themes:
- interdiction-blocker-vertex-cut
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
