id: J37
title: A branch-and-cut algorithm for the Edge Interdiction Clique Problem
authors:
- F. Furini
- I. Ljubic
- P. San Segundo
- Y. Zhao
year: 2021
kind: journal
venue: European Journal of Operational Research, Elsevier.
status: published
doi: 10.1016/j.ejor.2021.01.030
doi_url: https://doi.org/10.1016/j.ejor.2021.01.030
preprint_url: null
themes:
- interdiction-blocker-vertex-cut
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: Given a graph G and an interdiction budget k ∈ N, the Edge Interdiction Clique Problem (EICP)
  asks to find a subset of at most k edges to remove from G so that the size of the maximum clique, in
  the interdicted graph, is minimized. The EICP belongs to the family of interdiction problems with the
  aim of reducing the clique number of the graph. The EICP optimal solutions, called optimal interdiction
  policies, determine the subset of most vital edges of a graph which are crucial for preserving its clique
  number. We propose a new set-covering-based Integer Linear Programming (ILP) formulation for the EICP
  with an exponential number of constraints, called the clique-covering inequalities. We design a new
  branch-and-cut algorithm which is enhanced by a tailored separation procedure and by an effective heuristic
  initialization phase. Thanks to the new exact algorithm, we manage to solve the EICP in several sets
  of instances from the literature. Extensive tests show that the new exact algorithm greatly outperforms
  the state-of-the-art approaches for the EICP
