id: J07
title: Improved Rolling Horizon Algorithms for the Aircraft Sequencing Problem
authors:
- F. Furini
- M. P. Kidd
- C. Persiani
- P. Toth
year: 2015
kind: journal
venue: Journal of Scheduling, Springer.
status: published
doi: 10.1007/s10951-014-0415-8
doi_url: https://doi.org/10.1007/s10951-014-0415-8
preprint_url: null
themes:
- transportation-scheduling
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: "In a scenario characterized by a continuous Keywords Aircraft sequencing problem · MILP · Rolling\
  \ growth of air transportation demand, the runways of large air- horizon algorithms ports serve hundreds\
  \ of aircraft every day. Aircraft sequenc- ing is a challenging problem that aims to increase runway\
  \ capacity in order to reduce delays as well as the workload 1 Introduction of air traffic controllers.\
  \ In many cases, the air traffic con- trollers solve the problem using the simple “first-come-first-\
  \ Many researchers identify airports as the bottlenecks of the serve” (FCFS) rule. In this paper, we\
  \ present a rolling hori- air transportation system, where a relevant share of the delays zon approach\
  \ which partitions a sequence of aircraft into is often generated by an inefficient management of the\
  \ run- chunks and solves the aircraft sequencing problem (ASP) way capacities. The need for increasing\
  \ efficiency and capac- individually for each of these chunks. Some rules for decid- ity while reducing\
  \ delays persuade many researchers to inves- ing how to partition a given aircraft sequence are proposed\
  \ tigate runway scheduling problems. In this paper, we address and their effects on solution quality\
  \ investigated. Moreover, the aircraft sequencing problem (ASP) which is the problem two mixed integer\
  \ linear programming models for the ASP of optimally scheduling the departures and the arrivals oper-\
  \ are reviewed in order to formalize the problem, and a tabu ations of airport runways. The ASP can\
  \ be formally defined search heuristic is proposed for finding solutions to the ASP as follows. On input\
  \ we are given the set I = {1, 2, . . . , n} in a short computation time. Finally, we develop an IRHA\
  \ of aircraft (including both arrivals and departures) that will which, using different chunking rules,\
  \ is able to find solutions use the runway during a predefined time window. For each significantly improving\
  \ on the FCFS rule for real-world air aircraft i ∈ I , let t Ii be the scheduled arrival/departure time,\
  \ traffic instances from Milano Linate Airport. di the maximum acceptable delay and wi the cost associated\
  \ with one time unit of delay between the scheduled and actual arrival/departure times. For each ordered\
  \ pair of aircraft F. Furini PSL, Université Paris-Dauphine, 75775 Paris Cedex 16, France, (i 1 , i\
  \ 2 ) ∈ I × I , a minimum separation of t Si1 i2 time units must CNRS, LAMSADE UMR, 7243 Paris, France\
  \ be maintained between the actual arrival/departure times of e-mail: fabio.furini@dauphine.fr i 1 and\
  \ i 2 . The goal of the problem is to find a sequence of the given aircraft, together with the actual\
  \ arrival/departure M. P. Kidd · P. Toth DEI, University of Bologna, Viale Risorgimento 2, times z i\
  \ for each i ∈ I , so as to minimize the global weighted 40136 Bologna, Italy delay of the aircraft\
  \ with respect to their scheduled times, i.e. e-mail: martin.kidd@unibo.it to minimize the cost function:\
  \ P. Toth \x02 e-mail: paolo.toth@unibo.it wi (z i − t Ii ), i∈I C. A."
