id: J07
title: Improved rolling horizon approaches to the aircraft sequencing problem
authors:
- F. Furini
- M. P. Kidd
- C. Persiani
- P. Toth
year: 2015
kind: journal
venue: Journal of Scheduling, Springer.
status: published
doi: 10.1007/s10951-014-0415-8
doi_url: https://doi.org/10.1007/s10951-014-0415-8
preprint_url: null
themes:
- transportation-scheduling
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: In a scenario characterized by a continuous growth of air transportation demand, the runways
  of large airports serve hundreds of aircraft every day. Aircraft sequencing is a challenging problem
  that aims to increase runway capacity in order to reduce delays as well as the workload of air traffic
  controllers. In many cases, the air traffic controllers solve the problem by using the simple ``First-Come-First-Serve''
  (FCFS) rule. In this paper we present a rolling horizon approach which partitions a sequence of aircraft
  into chunks and solves the Aircraft Sequencing Problem (ASP) individually for each of these chunks.
  Some rules for deciding how to partition a given aircraft sequence are proposed and their effects on
  solution quality investigated. Moreover, two Mixed Integer Linear Programming (MILP) models for the
  ASP are reviewed in order to formalize the problem, and a tabu search heuristic is proposed for finding
  solutions to the ASP in a short computation time. Finally, we develop an IRHA which, by using different
  chunking rules, is able to find solutions significantly improving on the FCFS rule for real world air
  traffic instances from Milano Linate Airport.
