id: J32
title: A branch-and-price algorithm for the temporal bin packing problem
authors:
- M. Dell'Amico
- F. Furini
- M. Iori
year: 2020
kind: journal
venue: Computer & Operations Research, Elsevier.
status: published
doi: 10.1016/j.cor.2019.104825
doi_url: https://doi.org/10.1016/j.cor.2019.104825
preprint_url: null
themes:
- bin-packing-cutting-stock
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: We study an extension of the classical Bin Packing Problem, where each item consumes the bin
  capacity during a given time window that depends on the item itself. The problem asks for finding the
  minimum number of bins to pack all the items while respecting the bin capacity at any time instant.
  A polynomial-size formulation, an exponential-size formulation, and a number of lower and upper bounds
  are studied. A branch-and-price algorithm for solving the exponential-size formulation is introduced.
  An overall algorithm combining the different methods is then proposed and tested through extensive computational
  experiments.
