id: C04
title: A fast heuristic approach for train timetabling in a railway node
authors:
- F. Furini
- M. P. Kidd
year: 2013
kind: conference
venue: 6th International Network Optimization Conference (INOC 2013), Tenerife, Spain, May 2013 (8 pages).
status: published
doi: 10.1016/j.endm.2013.05.094
doi_url: https://doi.org/10.1016/j.endm.2013.05.094
preprint_url: null
themes: []
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: We consider a conflict-free scheduling problem which arises in railway networks, where ideal
  timetables have been provided for a set of trains, but where these timetables may be conflicting. We
  use a space-time graph approach from the railway scheduling literature in order to develop a fast heuristic
  which resolves conflicts by adjusting the ideal timetables while attempting to minimize the deviation
  from the ideal timetable. Our approach is tested on realistic data obtained from the railway node of
  Milan.
