id: J17
title: Improving the Approximated Projected Perspective Reformulation by Dual Information
authors:
- A. Frangioni
- F. Furini
- C. Gentile
year: 2017
kind: journal
venue: Operations Research Letters, Elsevier.
status: published
doi: 10.1016/j.orl.2017.08.001
doi_url: https://doi.org/10.1016/j.orl.2017.08.001
preprint_url: null
themes:
- decomposition-reformulation
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: We propose an improvement of the Approximated Projected Perspective Reformulation (AP2 R) for
  dealing with constraints linking the binary variables. The new approach solves the Perspective Reformulation
  (PR) once, and then use the corresponding dual information to reformulate the problem prior to applying
  AP2 R, thereby combining the root bound quality of the PR with the reduced relaxation computing time
  of AP2 R. Computational results for the cardinality-constrained Mean–Variance portfolio optimization
  problem show that the new approach is competitive with state-of-the-art ones. Mixed-Integer Non-Linear
  Problems Semi-continuous variables Perspective reformulation Projection Lagrangian relaxation Portfolio
  optimization
