id: J25
title: Benders Decomposition for Very Large Scale Partial Set Covering and Maximal Covering Location Problems
authors:
- J.F. Cordeau
- F. Furini
- I. Ljubic
year: 2019
kind: journal
venue: European Journal of Operational Research, Elsevier.
status: published
doi: 10.1016/j.ejor.2018.12.021
doi_url: https://doi.org/10.1016/j.ejor.2018.12.021
preprint_url: null
themes:
- covering-location-submodular
code_url: https://github.com/fabiofurini/LocationCovering
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: 'Covering problems constitute a fundamental family of facility location problems. This paper
  introduces a new exact algorithm for two important members of this family: i) the maximal covering location
  problem (MCLP), which requires finding a subset of facilities that maximizes the amount of customer
  demand covered while respecting a budget constraint on the cost of the facilities; and ii) the partial
  set covering location problem (PSCLP), which minimizes the cost of the open facilities while forcing
  a certain amount of customer demand to be covered. We study an effective decomposition approach to the
  two problems based on the branch-and-Benders-cut reformulation. Our new approach is designed for the
  realistic case in which the number of customers is much larger than the number of potential facility
  locations. We report the results of a series of computational experiments demonstrating that, thanks
  to this decomposition techniques, optimal solutions can be found very quickly for some benchmark instances
  with one hundred potential facility locations and involving up to 15 and 40 million customer demand
  points for the MCLP and the PSCLP, respectively.'
