id: C10
title: MIP Formulations for a Rich Real-world Lot-sizing Problem with Setup Carryover
authors:
- F. Focacci
- F. Furini
- V. Gabrel
- D. Godard and X. Shen
year: 2016
kind: conference
venue: 5th International Symposium on Combinatorial Optimization (ISCO 2016), Vietri sul Mare, Italy,
  May 2016 (12 pages).
status: published
doi: 10.1007/978-3-319-45587-7_11
doi_url: https://doi.org/10.1007/978-3-319-45587-7_11
preprint_url: null
themes: []
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: A rich lot-sizing problem is studied in this manuscript which comes from a real-world application.
  Our new lot-sizing problem combines several features, i.e., parallel machines, production time windows,
  backlogging, lost sale and setup carryover. Three mixed integer programming formulations are proposed.
  We theoretically and computationally compare these different formulations, testing them on real-world
  and randomly generated instances. Our study is the first step for eﬃciently tackling and solving this
  challenging real-world lot-sizing problem.
