id: C10
title: MIP Formulations for a Rich Real-world Lot-sizing Problem with Setup Carryover
authors:
- F. Focacci
- F. Furini
- V. Gabrel
- D. Godard and X. Shen
year: 2016
kind: conference
venue: 5th International Symposium on Combinatorial Optimization (ISCO 2016), Vietri sul Mare, Italy,
  May 2016 (12 pages).
status: published
doi: null
doi_url: null
preprint_url: null
themes: []
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: We study an extension of the Bin Packing Problem, where items consume the bin capacity during
  a time window only. The problem asks for finding the mini- mum number of bins to pack all the items
  respecting the bin capacity at any instant of time. Both a polynomial-size formulation and an extensive
  formulation are stud- ied. Moreover, various heuristic algorithms are developed and compared, including
  greedy heuristics and a column generation based heuristic. We perform extensive computational experiments
  on benchmark instances to evaluate the quality of the computed solutions with respect to strong bounds
  based on the linear programming relaxation of the proposed formulations
