id: J04
title: Models for the Two-Dimensional Two-Stage Cutting Stock Problem with Multiple Stock Size
authors:
- F. Furini
- E. Malaguti
year: 2013
kind: journal
venue: Computer & Operations Research, Elsevier.
status: published
doi: 10.1016/j.cor.2013.02.026
doi_url: https://doi.org/10.1016/j.cor.2013.02.026
preprint_url: null
themes:
- bin-packing-cutting-stock
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: 'Keywords: Cutting stock problem Mixed-integer programming models Computational experiments
  We consider a Two-Dimensional Cutting Stock Problem (2DCSP) where stock of different sizes is available,
  and a set of rectangular items has to be obtained through two-stage guillotine cuts. We propose and
  computationally compare three Mixed-Integer Programming models for the 2DCSP developing formulations
  from the literature. The first two models have a polynomial and pseudopolynomial number of variables,
  respectively, and can be solved with a general-purpose MIP solver. The third model, having an exponential
  number of variables, is solved via branch-and-price techniques. We conclude the paper describing the
  results of extensive computational experiments on a set of benchmark instances from the literature'
