id: J05
title: Generation of antipodal random vectors with prescribed non-stationary second-order statistics
authors:
- A. Caprara
- F. Furini
- A. Lodi
- M. Mangia
- R. Rovatti and G. Setti
year: 2014
kind: journal
venue: IEEE Transactions on Signal Processing, IEEE.
status: published
doi: 10.1109/tsp.2014.2302737
doi_url: https://doi.org/10.1109/tsp.2014.2302737
preprint_url: null
themes: []
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: A Look-Up-Table-based method is proposed to generate random instances of an antipodal n-dimensional
  vector so that its 2-nd order statistics are as close as possible to a given specification. The method
  is based on linear optimization and exploits column-generation techniques to cope with the exponential
  complexity of the task. It yields a LUT whose storage requirements are only O(n^3) and thus are compatible
  with hardware implementation for non-negligible n. Applications are shown in the fields of Compressive
  Sensing and of Ultra Wide Band systems based on Direct Sequence - Code Division Multiple Acces.
