id: J31
title: A lexicographic pricer for the fractional bin packing problem
authors:
- S. Coniglio
- F. D'Andreagiovanni
- F. Furini
year: 2019
kind: journal
venue: Operations Research Letters, Springer.
status: published
doi: 10.1016/j.orl.2019.10.011
doi_url: https://doi.org/10.1016/j.orl.2019.10.011
preprint_url: null
themes:
- bin-packing-cutting-stock
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: We propose an exact lexicographic dynamic programming pricing algorithm for solving the Fractional
  Bin Packing Problem with column generation. The new algorithm is designed for generating maximal columns
  of minimum reduced cost which maximize, lexicographically, one of the measures of maximality we investigate.
  Extensive computational experiments reveal that a column generation algorithm based on this pricing
  technique can achieve a substantial reduction in number of columns and computing time, also when combined
  with a classical smoothing technique from the literature.
