id: C02
title: Aircraft Sequencing Problems via a Rolling Horizon Algorithm
authors:
- F. Furini
- C. Persiani
- P. Toth
year: 2012
kind: conference
venue: 3rd International Symposium on Combinatorial Optimization (ISCO 2012), Athens, Greece, April 2012
  (12 pages).
status: published
doi: 10.1007/978-3-642-32147-4_25
doi_url: https://doi.org/10.1007/978-3-642-32147-4_25
preprint_url: null
themes: []
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: Aircraft sequencing on the runway is a challenging optimization problem that aims to reduce
  the delays and the air traffic controllers workload in a scenario characterized by a continuous growth
  of the air transportation demand. In this paper we consider the problem of sequencing both arrivals
  and departures on a single runway airport. We formalize the problem using a Mixed Integer Programming
  Model and we propose a rolling horizon solution approach. Computational results on real-world air traffic
  instances from the Milano Linate Airport are reported. The results show that the proposed approach is
  able to significantly improve on the First Come First Served (FCFS) sequence.
