id: J33
title: A Branch-and-Price Framework for Decomposing Graphs into Relaxed Cliques
authors:
- T. Gschwind
- S. Irnich
- F. Furini
- R. Wolfler Calvo
year: 2021
kind: journal
venue: INFORMS Journal on Computing, INFORMS.
status: published
doi: 10.1287/ijoc.2020.0984
doi_url: https://doi.org/10.1287/ijoc.2020.0984
preprint_url: null
themes:
- clique-stable-set
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: We study the family of problems of partitioning and covering a graph into/with a minimum number
  of relaxed cliques. Relaxed cliques are subsets of vertices of a graph for which a clique-defining property
  is relaxed, e.g., the degree of the vertices, the distance between the vertices, the density of the
  edges, or the connectivity between the vertices. These graph partitioning and covering problems have
  important applications in many areas such as social network analysis, biology, and disease spread prevention.
  We propose a unified framework based on branch-and-price techniques to compute optimal decompositions.
  For this purpose, new effective pricing algorithms are developed and new branching schemes are invented.
  In extensive computational studies, we compare several algorithmic designs, e.g., structure-preserving
  versus dichotomous branching and their interplay with different pricing algorithms. The finally chosen
  setup for the branch-and-price produces results that demonstrate the effectiveness of all components
  of the newly developed framework and the validity of our approach when applied to social network instances.
