id: J24
title: Theoretical and computational study of several linearisation techniques for Binary Quadratic Problems
authors:
- F. Furini
- E. Traversi
year: 2019
kind: journal
venue: Annals of Operations Research, Springer.
status: published
doi: 10.1007/s10479-018-3118-2
doi_url: https://doi.org/10.1007/s10479-018-3118-2
preprint_url: null
themes:
- quadratic-programming
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: We perform a theoretical and computational study of the classical Linearisation Techniques (LT)
  and we propose a new LT for Binary Quadratic Problems (BQPs). We discuss the relations between the Linear
  Programming (LP) relaxations of the considered LT for generic BQPs. We prove that for a specific class
  of BQP all the LTs have the same LP relaxation value. We also compare the LT computational performance
  for four different BQPs from the literature. We consider the Unconstrained BQP and the Maximum Cut of
  edge-weighted graphs and, in order to measure the effects of constraints on the computational performance,
  we also consider the quadratic extension of two classical combinatorial optimization problems, i.e.,
  the Knapsack and Stable Set problems.
