id: C12
title: A Branch-and-Benders-Cut Approach to Solve the Maximum Flow Blocker Problem
authors:
- I. Bentoumi
- F. Furini
- A.R. Mahjoub
- S. Martin
year: 2023
kind: conference
venue: 9th International Conference on Control, Decision and Information Technologies (CoDIT 2023), Rome,
  Italy, July 2023 (4 pages).
status: published
doi: 10.1109/codit58514.2023.10284073
doi_url: https://doi.org/10.1109/codit58514.2023.10284073
preprint_url: null
themes: []
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: Given a directed graph with capacities and interdiction costs associated with its arcs, the
  maximum flow blocker problem (MFBP) asks to find a minimum-cost subset of arcs to be removed from the
  graph in such a way that the remaining maximum-flow value does not exceed a given threshold. The MFBP
  has applications in telecommunication networks and in the monitoring of civil infrastructures, among
  others. We propose an integer linear programming formulation (ILP) with an exponential number of constraints,
  called Benders cut, for the MFBP. Accordingly, we derive a branch-and-cut algorithm to optimally solve
  the problem. Preliminary experimental results are reported to assess performance of the formulation
  and more precisely to determine the dimension of the problem that could be solved to proven optimality.
