id: J42
title: A Combinatorial Flow-based Formulation for Temporal Bin Packing Problems
authors:
- J. Martinovic
- N. Strasdat
- J. Valério de Carvalho
- F. Furini
year: 2023
kind: journal
venue: European Journal of Operational Research, Elsevier.
status: published
doi: 10.1016/j.ejor.2022.10.012
doi_url: https://doi.org/10.1016/j.ejor.2022.10.012
preprint_url: null
themes:
- bin-packing-cutting-stock
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: 'In this article, we consider two neighboring generalizations of the classical bin packing problem:
  the temporal bin packing problem (TBPP) and the temporal bin packing problem with fire-ups (TBPP-FU).
  In both cases, the task is to arrange a set of given jobs, characterized by a resource consumption and
  an activity window, on homogeneous servers of limited capacity. To keep the operational costs but also
  the energy consumption of this allocation as low as possible, two main optimization goals were identified
  in the literature. While TBPP is exclusively concerned with minimizing the number of servers in use,
  TBPP-FU additionally takes into account the switch-on processes required for their operation. In both
  cases, challenging integer optimization problems are obtained, which can differ significantly from each
  other despite the seemingly only marginal variation of the problems. In the literature, a branch-and-price
  method enriched with many preprocessing steps (for the TBPP) and compact formulations (for the TBPP-FU),
  which have been steadily improved by numerous reduction methods, have emerged as, currently, the most
  promising solution methods. In this paper, we present, in a sense, a unified solution approach for both
  problems based on graph theory. Any scientific contributions in this direction failed so far because
  of the exponential number of the necessary states and transitions. The approach we present in this article
  cannot change the theoretical exponentiality itself, but it can make it controllable by clever construction
  of the resulting graphs. In particular, this leads to the fact that for the first time all classical
  benchmark instances (and even larger ones) for the two problems can be solved -- in times that significantly
  improve those of the previous approaches.'
