id: C07
title: ILP and CP Formulations for the Lazy Bureaucrat Problem
authors:
- I. Ljubic
- F. Furini
- M. Sinnl
year: 2015
kind: conference
venue: 12th International Conference on Integration of Artificial Intelligence and Operations Research
  Techniques in Constraint Programming (CPAIOR 2015), Barcelona, Spain, May 2015 (15 pages).
status: published
doi: 10.1007/978-3-319-18008-3_18
doi_url: https://doi.org/10.1007/978-3-319-18008-3_18
preprint_url: null
themes: []
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: Lazy reformulations of classical combinatorial optimization problems are new and challenging
  classes of problems. In this paper we focus on the Lazy Bureaucrat Problem (LBP) which is the lazy counterpart
  of the knapsack problem. Given a set of tasks with a common arrival time and deadline, the goal of a
  lazy bureaucrat is to schedule a least profitable subset of tasks, while having an excuse that no other
  tasks can be scheduled without exceeding the deadline. Three ILP formulations and their CP counterparts
  are studied and implemented. In addition, a dynamic programming algorithm that runs is pseudo-polynomial
  time and polynomial greedy heuristics are implemented and computationally compared with ILP/CP approaches.
  For the computational study, a large set of knapsack-type instances with various characteristics is
  used to examine the applicability and strength of the proposed approaches.
