id: C09
title: Matheuristics for the Temporal Bin Packing Problem
authors:
- F. Furini and X. Shen
year: 2015
kind: conference
venue: 11th Metaheuristics International Conference (MIC 2015), Agadir, Morocco, June 2015 (13 pages).
status: published
doi: 10.1007/978-3-319-58253-5_19
doi_url: https://doi.org/10.1007/978-3-319-58253-5_19
preprint_url: null
themes: []
code_url: null
pdf:
  aam: true
  journal: true
  proof: false
note: null
abstract: We study an extension of the Bin Packing Problem, where items consume the bin capacity during
  a time window only. The problem asks for finding the minimum number of bins to pack all the items respecting
  the bin capacity at any instant of time. Both a polynomial-size formulation and an extensive formulation
  are studied. Moreover, various heuristic algorithms are developed and compared, including greedy heuristics
  and a column generation based heuristic. We perform extensive computational experiments on benchmark
  instances to evaluate the quality of the computed solutions with respect to strong bounds based on the
  linear programming relaxation of the proposed formulations.
